-- Bloco 10/69 - Clientes 1801 a 2000
INSERT INTO core.clientes (id_legado, nome, cpf, email, status, created_by, version)
VALUES
  ('2027590', 'SILVANA APARECIDA DE', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027602', 'ELIANA PEREIRA DE SO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027660', 'MARLENE FERREIRA GOM', NULL, 'LOJA@GMAIL.COM                                    ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027696', 'GERALDA CARLA OSTERN', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027720', 'DANIELE APARECIDA DE', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027754', 'DIVA SAMPAIO DA CONC', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027791', 'NILSON BATISTA SANTA', NULL, 'LOJALANCASTER@GMAIL.COM                           ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027829', 'MARIA INES FARIAS DO', NULL, 'SUZANO@LANCASTER.COM.BR                           ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027863', 'MARIA DA CONCEIÇÃO S', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027892', 'EVA MARTINS DA SILVA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027902', 'MIDIAN PEREIRA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027926', 'FABRICIO DE OLIVIERA', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2027991', 'RAFAEL DOS SANTOS CE', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028022', 'MAURICIA APARECIDA D', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028034', 'MANOEL ZITO JESUS PR', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028036', 'BRUNO RIBEIRO DA SIL', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028070', 'SIDNEI DOS SANTOS VI', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028085', 'VANDA LUZ', NULL, 'lojamaua@gmail.com                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028087', 'EULALIA RODRIGUES LE', NULL, 'LOJAMAUA@GHMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028107', 'JOSE APARECIDO SOARE', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028143', 'JAQUELINE MARIA HONO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028157', 'AMANDA APARECIDA MAI', NULL, 'SUZANO@LANCASTER.COM.BR                           ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028221', 'APARECIDO GERALDO SI', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028227', 'VANILSA M LIMA VENTR', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028257', 'MARIS JOSE BARROS', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028270', 'ROSANA BATISTA DOS S', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028279', 'CLIZEIDE SOARES LINS', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028315', 'MARLY COSTA DOS SANT', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028383', 'MARIA ISABEL BOMFIM', NULL, 'SUZANO@LANCASTER.COM.BR                           ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028407', 'MANOEL ALMEIDA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028461', 'NAYARA BEUTA DE SOUZ', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028476', 'JHONATHAN HENRIQUE D', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028521', 'ANA KAROLYNE PEREIRA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028583', 'LUCAS KAUE BASILIO D', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028596', 'ROSEMEIRE NASCISMENT', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028628', 'ERICA AUGUSTA SILVA', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028685', 'ANGELICA INES BASTOS', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028710', 'JEAN CARLOS SILVA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028727', 'CARLOS TOSHIRO HIROT', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028728', 'ROSELI XAVIER MARTIN', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028734', 'OLIVIA GOMES PEREIRA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028822', 'WAGNER ADRIANO MARTI', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028858', 'KARINA DA CONCEIÇÃO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028891', 'GABRIELE MARIA SILVA', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028894', 'ELIETE APARECIDA SAN', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028925', 'MARIA DA PAZ CANDIDA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028927', 'IVALDO INACIO DA SIL', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028938', 'REGINALDO PEREIRA DE', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028941', 'ZIRLENE VIEIRA CARDO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2028979', 'SUZANA FLAVIA DOS SA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029017', 'ALEXANDRE APARECIDO', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029022', 'JOSE JACKSON SOARES', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029025', 'CICERA DE OLIVEIRA B', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029067', 'VANICE PEREIRA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029183', 'PAULO CESAR LEITE DA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029188', 'DANIELA RAMOS DE LUN', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029360', 'ANETE PACHECO DO NAS', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029417', 'DENISE HANASHIRO', NULL, 'SUZANO@OTICASWLANCASTER.COM.BR                    ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029514', 'ALFREDO NICKEL', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029535', 'GIOVANA ALVES CHIARO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029546', 'LUCIMARA SPERANDIO', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029607', 'MARIA DE LOURDES SAL', NULL, 'maua@oticas.com.br                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029636', 'WAGNER CAVALCANTE DE', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029645', 'FRANCISCA DE NAZARE', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029662', 'SILVANA SILVA PINHEI', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029681', 'GILVANEIDE MARIA DE', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029717', 'EDIVAL LOPES BARRETO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029732', 'JOAO ROBERTO PANAREL', NULL, 'SUZANO@OTICASALANCASTER.COM.BR                    ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029762', 'FABIANA R. DOS SANTO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029794', 'SAMANTA NUNES DE OLI', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029799', 'MARIA NEUSA MATEUS', NULL, 'MAUA@OTICASLANCASTER.COM.BR                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029830', 'LUCIDALVA DE ARAUJO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029841', 'ADRIANA ANDRADE NOGU', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029850', 'JOSE AUGUSTO DE MELO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029876', 'PAULA DOS SANTOS BON', NULL, 'MAUA@OTICAS.COM                                   ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029879', 'RUBENS JOSE DA SILV', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2029932', 'MEIRE ELEN DE ANDRAD', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030031', 'MARIA DA CONSOLAÇÃO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030033', 'JULIANA DO NASCIMENT', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030034', 'ELAINE CRISTINA FERR', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030035', 'MARIA ILMA DANTAS DO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030037', 'ELAINE CARLOS PEREIR', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030038', 'MARCELO CARDOSO DA S', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030042', 'CRISTINA TEIXEIRA DO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030044', 'REGINA CELIA DE ANDR', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030045', 'MARIA DE JESUS LEITE', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030049', 'FRANCILENE SANTOS VI', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030050', 'VANDERLAN ANTONIO DI', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030053', 'NEIDE SATOMI SATO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030058', 'FRANCINEIDE MENDES D', NULL, 'maua@oticas.com.br                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030059', 'CLAUDIO PEREIRA DE S', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030063', 'DOLORES DE FATIMA DA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030064', 'GERALDO CARLOS DO CA', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030068', 'LAURINDO CANDIDO DE', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030096', 'JUCILAINE SANTIAGO D', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030174', 'SONIA REGINA DE COEL', NULL, 'OTICAMAUA@GMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030175', 'CLODOALDO PACHECO', NULL, 'LOJAMAU@GMAI.COM                                  ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030178', 'EDIVANILDA FRUTADO F', NULL, 'OTICAMAUA@GMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030179', 'LOURDES DE JESUS CAR', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030182', 'MARINA APARECIDA DA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030183', 'MARIA DE FATIMA MART', NULL, 'OTICAMAUA@GMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030184', 'ALDENIR DE JESUS GON', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030210', 'LUCIANA APARECIDA PO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030250', 'LUCAS BATISTA DOS SA', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030251', 'JOSEFA SEVERINA SOAR', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030340', 'JULYELLY INACIO DE F', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030345', 'IVANILDA PEREIRA DA', NULL, 'MAUA@OTICASLANCASTER.COM.BR                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030347', 'IZETE ROBERTA DOS SA', NULL, 'MAUA@OTICASLANCASTER.COM.BR                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030441', 'MATHEUS LEONARDO', NULL, 'suzano@oticaslancaster.com.br                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030543', 'IVANILDO R DE AL', NULL, 'maua@oticaslancaster.com.br                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030545', 'GABRIELE MEDINA ROCH', NULL, 'maua@oticaslancaster.com.br                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030547', 'MARCIARIA SANTOS DE', NULL, 'maua@oticaslancaster.com.br                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030550', 'MARTA BICALHO DA S', NULL, 'maua@oticaslancaster.com.br                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030551', 'MICHELLY DAIANA SILV', NULL, 'maua@oticaslancaster.com.br                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030552', 'JANAINA CANATO', NULL, 'maua@oticaslanaster.com.br                        ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030561', 'GABRIELA FERREIRA BA', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030562', 'ROSELI BORGES QUINTO', NULL, 'maua@oticalancaster.com.br                        ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030566', 'ERIK P', NULL, 'maua@oticaslancaster.com.br                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030575', 'AUDREI ALONSO FIRMI', NULL, 'maua@oticaslancaster.com.br                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030585', 'MARIONE LANZANA', NULL, 'maua@oticaslancaster.com.br                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030587', 'CLAUDIA GUEDES ANTUS', NULL, 'maua@oticalancaster.com.br                        ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030666', 'INDIA PEREIRA COSTA', NULL, 'maua@oticalancaster.com.br                        ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030702', 'LARISSA GABRIELLE SA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030703', 'JOSE EDMAR MAURA LUZ', NULL, 'OTICAMAUA@GMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030705', 'CRISTIANE CARDINHO P', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030710', 'MARIA PRISCILA DE MA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030715', 'HIAGO COSTA DE OLIV', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030717', 'JORGE DE JESUS SANTO', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030723', 'CLAUDIA SOARES DA PE', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030727', 'MARIA DO SOCORRO CAL', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030733', 'ANDRESSA DA CONCEIÇÃ', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030828', 'RAYANE DA CONCEIÇÃO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030837', 'MARIA JOCIANE GOMES', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030842', 'ANDREIA RODRIGUES RI', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030846', 'ROBINSON LUIZ PEREIR', NULL, 'SUZANO@OTICASLANCASTER.COM                        ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030848', 'DALVA ROQUE ROSA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030870', 'JAQUELIINE DA SILVA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030879', 'ELISANGELA GOES DA S', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030898', 'JOSE ALZEMIR CARVALH', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030917', 'JOÃO CARLOS DA SILV', NULL, 'maua@oticas.com.br                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030921', 'VICENTE RODRIGUES FE', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030931', 'JOSE GOMES DA SILVA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030933', 'MARIA EDILMA LEAL DE', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2030935', 'BIANCA CONCEIÇÃO DE', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031006', 'AMARO SEBASTIÃO DO N', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031018', 'PATRICIA DE OLIVEIRA', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031038', 'GRAZIELE CUSTODIO MA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031064', 'LETICIA SUNAMITA DOS', NULL, 'MUA@OTICASLANCASTER.COM.BR                        ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031067', 'FERNAANDO DOS SANTOS', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031069', 'PAULA DEOLINDA FERRE', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031070', 'FRANCILENE MACIEL SO', NULL, 'MAUA@OTICALANCASTER.COM.BR                        ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031071', 'MAGDA VIANA DOS SANT', NULL, 'MAUA@OTICAS.COMBR                                 ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031072', 'JERUZA SILVA DO SANT', NULL, 'LOJAMAUA@HMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031073', 'MARIA APARECIDA DA G', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031074', 'ELIANE NORBERTO DOUR', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031076', 'MARCIIA DOS SANTOS', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031077', 'AMANDA PLACHESKI BAT', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031078', 'MARLI NUNES SILVA', NULL, 'OTIMALANCASTERMAUA@GMAIL.COM                      ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031101', 'NATHIANE PEDROSO JAB', NULL, 'lojamaua@gmail.com                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031112', 'KLEBER RUIZ DE OLIVE', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031117', 'OSMARINA PEREIRA GOM', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031166', 'FERNANDA SANTOS BARB', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031167', 'LUCIA ALDENORA DO NA', NULL, 'OTICALANCASTERMAUA@GMAIL.COM                      ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031169', 'MARIA APARECIDA CARD', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031173', 'LINDINALVA FRANCELIN', NULL, 'OTICALANCASTERMAUA@GMAIL.COM                      ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031177', 'REGINA BORGES RODRIG', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031192', 'ADRIANA MARCIA GOMES', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031196', 'FRANCISCA ANTONIA DE', NULL, 'FRANCISCAC235@GMAIIL.COM                          ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031197', 'GILSEMAR VIEIRA MART', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031206', 'DENILSON DA SILVA FI', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031207', 'ALINE MOURA SILVA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031208', 'SIMONE MELO DA SILVA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031212', 'ERIKA NATHANY DE FAR', NULL, 'OTICALANCASTER@GMAIL.COM                          ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031214', 'ALEXANDRA NASCIMENTO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031246', 'MARCIA FARIAS DO VAL', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031250', 'JOAO DA SILVA DE CAS', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031255', 'ERICA SANTOS NASCIME', NULL, 'SUZANO@OITCASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031266', 'RAPHAEL ANTONIO DOS', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031274', 'ERIKA BORGES DOS SAN', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031302', 'VICTOR COSTA DURAES', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031304', 'MARIA APARECIDA SOUZ', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031308', 'TATIELE APARECIDA SI', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031326', 'FRANCISCO VALDIMAR M', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031330', 'MARIA ROSINETE GOMES', NULL, 'LOJAMAUA@GMAIL.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031350', 'REGINALDA SANTOS SIL', NULL, 'OTICAMAUA@GMAI.COM                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031356', 'GABRIEL DA SILVA', NULL, 'oticamaua@gmail.com                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031360', 'JOSE SEVERINO DA SI', NULL, 'OTICAMAUA@GMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031362', 'MARIA APARECIDA LIBO', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031366', 'ANDRISON MENDES DA S', NULL, 'MAUA@OTICASLANCASTER.COM.BR                       ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031373', 'LENILDES MARIA DOS S', NULL, 'OTICAMAUA@GMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031388', 'MARIA JOSE SANTO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031398', 'NICOLE NUNES', NULL, 'OTICAMAUA@GMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031407', 'JILMARA OLIVEIRA DA', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031411', 'BRUNO ALVES SANTOS.', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031427', 'JOSE MORELLO', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031434', 'LUZENI GAMA CONCEICA', NULL, 'maua@oticas.com.br                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031437', 'ZILDA AUGUSTA DA SIL', NULL, 'MAUA@OTICAS.COM.BR                                ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031441', 'EROTILDE CAPUCHO DOS', NULL, 'OTICAMAUA@GMAIL.COM                               ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031455', 'MARIA VALENTINA CARD', NULL, 'SUZANO@OTICASLANCASTER.COM.BR                     ', 'ATIVO', 'MIGRACAO_VIXEN', 1),
  ('2031501', 'ANTONIO CARLOS BATIS', NULL, 'SUZANO@OTICASLANCASTER.COM                        ', 'ATIVO', 'MIGRACAO_VIXEN', 1);