-- Bloco 66/69 - Clientes 13001 a 13200
INSERT INTO core.clientes (id_legado, nome, cpf, email, status, created_by, version)
VALUES
  ('2135008', 'JANY CAROLINE', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135009', 'JOICE DE ALMEIDA', NULL, 'almeidajoice542@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135010', 'JOSE APRIGIO DA SILVA', NULL, 'joaprigio123@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135011', 'JOSE ROBERTO DOS SANTOS', NULL, 'joseroberto@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135012', 'jose roberto paiatto', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135013', 'JOSE ROBERTO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135014', 'JULIA ANNE MACIEL PINHO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135015', 'leni de souza veras', NULL, 'leni.veras07@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135016', 'LIDIA MARIA LISBOA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135017', 'LUCINEIA DOS SANTOS', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135018', 'luiz felipe candido', NULL, 'luizfelipecandido1999@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135019', 'MARCIO LUIZ ANTONIO DE OLIVEIRA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135020', 'maria antonia da silva', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135021', 'MARIA DA MERCES SILVA SANTOS', NULL, 'mariamercesss1952@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135022', 'MARIA DEUZIMAR ROCHA SHIGENO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135023', 'MARIA LUCIA DE SOUZA', NULL, 'lucia.maria.sousa2014@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135024', 'MARIA ROSANGELA BARROS DA SILVA REGO', NULL, 'm.rose.silva64@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135025', 'matheus henrique souza silva', NULL, 'jessicajainemoreira27@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135026', 'MAURO ROBERTO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135027', 'MEIRE NUNES DE ARAUJO', NULL, 'meiren@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135028', 'miria martins souza de moura', NULL, 'miriammartins2607@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135029', 'NATALIA SANCHES VIANA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135030', 'NILSON AMANCIO (FILHA THAIS)', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135031', 'ONLANDE FREIRE DA SILVA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135032', 'OSVALDO LUIZ ROCHA MENEZES', NULL, 'olrgalo@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135033', 'patricia borges ferreira', NULL, 'borgespatricia@365.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135034', 'paulo augusto da silva', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135035', 'PEDRO ALVES DE LIMA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135036', 'pedro augusto cavalcanti', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135037', 'rinaldo medeiros furtado', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135038', 'ROBERTO PEZZUOL', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135039', 'ROSANAA APARECIDA FIDALGO', NULL, 'ro.fidalgo@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135040', 'ROSELI OBLASSER KOHLEMANN', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135041', 'rosineide santos liam severiano', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135042', 'rosinete tavares da silva', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135043', 'SERGIO COQUITE KURIBAYASHI', NULL, 'coquite@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135044', 'silvana rejane ferreira vieira', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135045', 'Valdivo pereira de souza', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135046', 'VALDIVO PERERIRA DE SOUZA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135047', 'marcelo vieira barbosa', NULL, 'fabianamariajesus1112@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135048', 'dasdores francisca in~es da fonseca', NULL, 'cfcdorinha@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135049', 'NEUZALINA VIEIRA MONTEIRA SOARES', NULL, 'vieiramonteorog@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135050', 'JOSE ERNESTO MARTINS', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135051', 'ODETE DE LOURDES MENDES TERAGI', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135052', 'ORLANDO MARTINS DOS SANTOS', NULL, 'orlandomsantos760@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135053', 'marcos antonio da silva', NULL, 'sarnei.marcos@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135055', 'MARIA IMACULADA DA CONCEICAO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135056', 'VALDEMICE BATISTA DOS SANTOS', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135057', 'MARIA MADALENA FONSECA PINTO', NULL, 'mariam@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135058', 'jose laercio rosa', NULL, 'rosalaercio316@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135059', 'ANESIA CARVALHO COELHO', NULL, 'elisangela.coelho12@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135060', 'CLRIDE  MARIA  DE  SANTANA  BRAGA', NULL, 'cleidepsico1@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135061', 'DELZUINA DE  SOUZA BARBOZA', NULL, 'maurorocha.barboza@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135062', 'claudete ramon felin gois', NULL, 'claudeteramon@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135063', 'SONIA FELIZARDO PEREIRA', NULL, 'mf3131069@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135064', 'FRANCISCO DE ASSIS FERNEZI JUNIOR', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135065', 'akiko eguchi', NULL, 'akieguchi@outloock.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135066', 'cecera dos santos', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135067', 'sandra regina valdagno', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135068', 'vitoriano pereira souza', NULL, 'vitvitoriano85@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135069', 'celia maria barbosa dos santos', NULL, 'cmamabarbosa50@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135070', 'JONAS  aparecido guimaraes', NULL, 'annamodasss@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135072', 'CICERO ROBERTO DA SILVA', NULL, 'c.roberto0929@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135073', 'mariana rosa de jesus do acrmo', NULL, 'rosamariana709@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135074', 'claudinei dos santos', NULL, 'claudinei.santos.62@outlook.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135075', 'ROSE MEIRE SATURNINO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135076', 'francisco marinho mota', NULL, 'francisco@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135077', 'paulo do carmo', NULL, 'pauloscarmo2020@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135078', 'vera lucia pires da silva', NULL, 'verinha938@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135079', 'ROSA SHIZUKA FURUSHIMA DOS PASSOS', NULL, 'rosa.furushima1961@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135080', 'joao bosco da silva', NULL, 'j.boscogms@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135081', 'VITALINA MARIA DE SENA SILVA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135082', 'valdivo pereira de souza', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135083', 'marco antonio de ataide', NULL, 'marcoantoniodeataide@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135084', 'MARIA FERREIRA ALVES DE SOUZA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135085', 'maria ferreira', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135086', 'Elon cordeiro dos santos', NULL, 'ronielesuzano2017@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135087', 'CLEONICE PEREIRA CEZAR MOREIRA', NULL, 'cleonicepereiracezar@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135088', 'SUELI MOREIRA DOS SANTOS', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135089', 'cloves cora da silva', NULL, 'clovescorasilva@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135090', 'ailton barbosa dos santos', NULL, 'barbosa.ailton2018@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135091', 'maria de souza castro', NULL, 'mariacastroheloisa@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135092', 'MARILU CANDIDA JACOB PEREIRA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135094', 'HEITOR RODRIGUES DE FIGUEIREDO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135095', 'MANOEL TELES DE MENEZES LIMA', NULL, 'dinhotellesmenezes@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135096', 'JORGE LUIZ OLIVEIRA DE SANTANA', NULL, 'santanaluizjorge@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135097', 'JOAO ROCHA DE OLIVEIRA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135098', 'CLAUDIO R DE LIMA', NULL, 'lucianalucas2006@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135099', 'ROSIMARY SANTANA CORDEIRO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135100', 'RONALDO SILVIO DE OLIVEIRA', NULL, 'ronaouvirecrer@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135101', 'ELSON RODRIGUES', NULL, 'nelsonr010@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135102', 'ezequiel pereira soldado', NULL, 'ezequiel.soledade@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135103', 'albertina da costa', NULL, 'tian.berta@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135104', 'doralice rodrigues vieira', NULL, 'doralice@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135105', 'izildinha aparecida lorato de souza', NULL, 'izildinhalorato@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135106', 'claudio cardoso dos santos', NULL, 'claudiocardosodossantos13@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135107', 'MARIA DO SOCORRO GONCALVES DA SILVA SOUZA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135108', 'maria cecilia tavares', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135109', 'aurivaldo antonio corocher', NULL, 'aurivaldocorocher@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135110', 'FRABCISCA MARGARETH GADELHA MARTINS', NULL, 'oticaslasncaster@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135111', 'DELCIRA VIEIRA SANTOS', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135112', 'maria francisca veloso antunes', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135113', 'silvana torres andre da silva', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135114', 'nilson amancio filho', NULL, '217nilson@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135115', 'MARIA DE FATIMA DE ALMEIDA BISERRA', NULL, 'paty.ipog@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135117', 'silvana alves jansen lopes', NULL, 'sil.jansen@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135118', 'EDSON SOUZA DE ALMEIDA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135119', 'jose policarpo da silva', NULL, 'pollycarpos@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135120', 'obede  de oliveira rocha', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135121', 'IVANILDA RIBEIRO ALVES', NULL, 'rona.oliveira27@gmaail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135122', 'LUIZ CARLOS DO NASCIMENTO MELLO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135123', 'NOEMIA AVELINO DE SOUZSA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135124', 'CLEUSA DOS SANTOS', NULL, 'cleusacasanini@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135125', 'neusa lima de souza', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135126', 'RUTH CORREA DA  CUNHA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135127', 'WESLEY DA SILVA  ANDRADE', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135128', 'EUNICE APARECIDA DE SOUZA', NULL, 'eunicepalmesciano@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135129', 'Cicero Jose Ferreira', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135130', 'CARMEN LUCIA CERQUEIRA FERNANDES', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135131', 'ines da silva mesquita', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135132', 'raraquel paulino gomes', NULL, 'raquelpaulinogomes@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135133', 'maria neide da silva', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135134', 'SOLANGE SILVA DANEZI', NULL, 'solangeeesilvaaa65@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135135', 'maria rsangela baros da silva rego', NULL, 'm.rose.silva64@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135136', 'JULCIMARA APARECIDA DOS SANTOS', NULL, 'julcimara@pro.educacao.sp.gov.br', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135137', 'antonio carlos polidori', NULL, 'polidori47@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135138', 'marcos massayuki takatori', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135139', 'aparecido delmiro dos santos', NULL, 'lucilene@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135140', 'ULISSES ROBERTO DOS SANTOS', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135141', 'eli bezerra', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135142', 'marilza franquelino da silva', NULL, 'franquelinomarilza@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135143', 'GILBERTO DO SANTOS OLIVEIRA', NULL, 'gilbaruk@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135144', 'gilvania maria dos santos moura', NULL, 'jourdanamoura4@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135145', 'valdir alves', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135146', 'WILSON CARLOS DE ANDRADE', NULL, 'cassia_rock@yahoo.com.br', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135147', 'luiz fernando ferreira ramos', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135148', 'ROSIMEIRE CREPALDI CACOLA', NULL, 'rosecrepaldi2011@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135149', 'paulo rogerio  guimaraes', NULL, 'pauinhoguima45@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135150', 'marina lucia de souza', NULL, 'mararosa190@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135151', 'helington oliveira dela torre', NULL, 'helington@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135152', 'Ana maria soares', NULL, 'anacristinamenotte13@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135153', 'VALDECI LOPES DA SILVA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135154', 'CLEIDE MARIA SANTANA', NULL, 'cleidepsicol@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135155', 'antonio bezerra ferreira', NULL, 'antonio05055492@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135156', 'MARIA DAS GRACAS EUGeNIA DA SILVA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135157', 'massae yonamine taira', NULL, 'massaeyonamine@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135158', 'LEANDRO LOPES', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135159', 'hermes macedo', NULL, 'hermes.radio.macedo@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135160', 'katia maria duarte', NULL, 'katiamariaduarte2@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135161', 'LUIZ CLAUDIO VINHOLI BOMFIM', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135162', 'ZENILDA AUGUSTA DA SILVA', NULL, 'zenilda@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135163', 'roberto danizete tavares', NULL, 'robertod.tavares@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135164', 'ROBERTO DONIZETE TAVARES', NULL, 'roberto.tavares@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135165', 'zilda aparecida moreira de oliveira', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135166', 'ROSA MARIA LEAL DE LIMA', NULL, 'emidio@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135167', 'MANOEL FRANCELINO DE OLIVEIRA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135168', 'manuel liberati', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135169', 'maria das dores lima ferreira', NULL, 'karenkutsala25@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135170', 'RICARDO DIAS DA SILVA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135172', 'MARIA JOSE BORGES DOS SANTOS', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135173', 'EDSON LUCAS DE ALMEIDA', NULL, 'edsonlucasalmeida9@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135174', 'RUIVALDO CAETANO', NULL, 'ruivaldocaetano@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135175', 'VICTOR KUNIKA TSU HORIKOME', NULL, 'senimir@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135176', 'guiseppe maza macedo', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135177', 'Luiz Garcia  Leal', NULL, 'luiz.g.leal@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135178', 'LUIZ GARCIA LEAL', NULL, 'luiz.g.leal@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135179', 'maria  aparecida da silva', NULL, 'gilvaniarrodrigues40977@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135180', 'tereza cristina borges da silva', NULL, 'terezacristinasilva1965@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135181', 'SHEILA RIBEIRO FERREIRA FERNANDEZ', NULL, 'liicencasterra7@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135182', 'MARIA NAZARETH  AGUIAR DE OLIVEIRA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135183', 'elianice pinheiro pinto', NULL, 'vanderlei.lerin@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135184', 'ELENICE PINHEIRO PINTO', NULL, 'elenicepinto@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135185', 'OSWALDO DOS SANTOS', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135186', 'vcleide sebatsiao', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135187', 'SILVANA MARIA RODRIGUES', NULL, 'marirodrige@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135188', 'Maria Imaculada do Carmo Shinkado', NULL, 'taty.mello0607@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135189', 'maria jose for', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135190', 'MARIA DAS GRACAS SILVA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135191', 'nelma cavalcante santana', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135192', 'alberto bento  da silva', NULL, 'dmartinssilva@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135193', 'edson da silva felix', NULL, 'felixedson062@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135194', 'georgina maria dos santos', NULL, 'georgina.maria1950@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135195', 'MARIA NEUZA SANTOS DA SILVA', NULL, 'neuzasilva2021@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135196', 'IRACEMA DA SILVA CALIXTO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135197', 'simone fragnan', NULL, 'camilafragma-1309@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135198', 'Cristiane das gracas viana', NULL, 'crisssanchesv@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135199', 'MARIA JOSE SOUZA OLIVEIRA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135200', 'VICENTE EDUARDO', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135201', 'MARIAS SANDRA DA SILVA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135202', 'zuleide m. s de araujo', NULL, 'zuzu.0811maria@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135203', 'Rafael Silveira  Oliveira', NULL, 'olibertadorleonel@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135204', 'antonio armando pereira da silva', NULL, 'antonio@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135205', 'lucas barreto', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135206', 'JOSE CLAUDIO DE SOUZA', NULL, 'joseclaudio@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135207', 'MILEIDE CRISTINA', NULL, 'mileidedelima@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135210', 'MARIA JOSE  SOUZA', NULL, NULL, 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135211', 'jailton santana costa', NULL, 'jailton@gmail.conm', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135212', 'PAULO COLOMBO DOS SANTOS', NULL, 'colombopaulo@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135213', 'carlos alberto da silva rocha', NULL, 'pattysilvacel@hotmail.com', 'ATIVO', 'MIGRACAO_OS', 1),
  ('2135214', 'ROSANGELA CELESTINO', NULL, 'rosangelacelestinoro@gmail.com', 'ATIVO', 'MIGRACAO_OS', 1);